### ISSUE TITLE
Variable names shadowing built-in names

### ISSUE THREAD

**Issue by the-zebulan** [DangerOnTheRanger/fuzzbuzz#4]
I am getting a few warnings about shadowing built-in names on some of your examples.
- `sequence.py, sequence_fast.py & recursion.py` -> `Shadows built-in name 'next'`
- `fastest.py` -> `Shadows built-in name 'list'`

Suggestions:
- `next_item`

and
- `fuzzbuzz_list`
- `my_list`

It's really up to you but the names should probably be changed.

**Comment by DangerOnTheRanger** [comment]
Oops, thanks for the heads up.

Fixed with:
- 5a2e044ea57b89d6a841f421a763e2b208c199a6
- a9b7f14a19eea382cb34621136072d4b8665b182
- 2869f22a627d4d9ce4f39629fb476d2a7da7ceef
- ede2c04aa37843cd904b2f279a03356c6dec4a93

**Comment by the-zebulan** [comment]
Looks good, thanks!
